batch_type: numel
# batch_bins: 16000000
# batch_bins: 4000000
batch_bins: 160000000
# batch_bins: 320000000
# batch_size: 256
accum_grad: 1
max_epoch: 250
patience: 10
# The initialization method for model parameters
init: xavier_uniform
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

encoder: transformer
encoder_conf:
    output_size: 512
    attention_heads: 8
    linear_units: 2048
    num_blocks: 10
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d
    normalize_before: true


text_preencoder: embed
text_preencoder_conf:
    output_size: 512
    padding_idx: 2

text_encoder: transformer
text_encoder_conf:
    output_size: 512
    attention_heads: 8
    linear_units: 2048
    num_blocks: 4
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d
    normalize_before: true

shared_encoder: transformer
shared_encoder_conf:
    output_size: 512
    attention_heads: 8
    linear_units: 2048
    num_blocks: 2
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: identity
    normalize_before: true

decoder: transformer
decoder_conf:
    attention_heads: 8
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0

model_conf:
    ctc_weight: 0.2
    lsm_weight: 0.1
    text_in_mask_ratio: 0.2
    swap_embedding_ratio: 0.1
    swap_embedding_position: "before_shared"
    length_normalized_loss: false
    subsample_factor: 4

optim: adam
optim_conf:
    lr: 0.001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 50000

frontend_conf:
  n_fft: 512
  win_length: 400
  hop_length: 160

specaug: specaug
specaug_conf:
    apply_time_warp: true
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 30
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_range:
    - 0
    - 40
    num_time_mask: 2
unused_parameters: True
